# services/data_preprocessor/cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    # Note: $PROJECT_ID is an auto-available substitution in Cloud Build
    - 'europe-west9-docker.pkg.dev/$PROJECT_ID/data-preprocessor-repo/data-preprocessor-service:v1'
    - '.' # Build context (current directory where Dockerfile is)
  # 'dir' is not needed if cloudbuild.yaml is in the same dir as Dockerfile

images:
# Image to push to Artifact Registry
- 'europe-west9-docker.pkg.dev/$PROJECT_ID/data-preprocessor-repo/data-preprocessor-service:v1'